---

- name: Set up Debian
  when: ansible_facts['os_family'] == "Debian"
  block:

    - name: Update package repository cache
      apt:
        update_cache: yes

    - name: Install ClamAV and related services
      package:
        name:
          - clamav
          - clamav-daemon
        state: present

    - name: Enable ClamAV service at startup
      systemd:
        name: clamav-daemon
        enabled: yes
        state: started

    - name: Stop ClamAV service temporarily to update db
      systemd:
        name: clamav-daemon
        state: stopped

- name: Set up Archlinux
  when: ansible_facts['os_family'] == "Archlinux"
  block:

    - name: Install ClamAV and related services
      package:
        name:
          - clamav
        state: present

    - name: Enable ClamAV service at startup
      systemd:
        name: clamav-daemon
        enabled: yes
        state: started

    - name: Stop ClamAV service temporarily to update db
      systemd:
        name: clamav-daemon
        state: stopped

- name: Set up Fedora
  when: ansible_distribution == "Fedora"
  block:

    - name: Install ClamAV and related services
      package:
        name:
          - clamav
          - clamd
          - clamav-update
        state: present

    - name: Enable ClamAV service at startup
      systemd:
        name: clamav-freshclam
        enabled: yes
        state: started

    - name: Stop ClamAV service temporarily to update db
      systemd:
        name: clamav-freshclam
        state: stopped

- name: Pause for 5 seconds to let app stop locking the filesystem
  ansible.builtin.pause:
    seconds: 5

- name: Update ClamAV virus database
  command: freshclam
  register: freshclam_output
  changed_when: "'bytecode.cvd is up to date' not in freshclam_output.stdout"

- name: Add Known False Positives
  ansible.builtin.copy:
    src: templates/false-positives.sfp
    dest: /var/lib/clamav/false-positives.sfp # Could probably variablise but it'll do for now
    owner: root
    group: root
    mode: 0555

- name: Finalise Setup Fedora
  when: ansible_facts['os_family'] == "Fedora"
  block:
  - name: Start ClamAV service if not running
    systemd:
      name: clamav-freshclam
      state: started

- name: Finalise Setup Debian & Archlinux
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Archlinux"
  block:
  - name: Start ClamAV service if not running
    systemd:
      name: clamav-daemon
      state: started